config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/new',    to: 'games#new'
  get  '/game',    to: 'games#play'
  get  '/stats',    to: 'games#stats'
  post '/update', to: 'games#update'

  get  '/about',   to: 'static_pages#about'
  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  def generate_word
    words = File.read('app/assets/words.txt').lines
    return words.select {|l| (4..20).cover?(l.strip.size)}.sample.strip
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello world"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def generate_word
    words = File.read('app/assets/words.txt').lines
    return words.select {|l| (4..20).cover?(l.strip.size)}.sample.strip
  end
  
  def new
    solution = generate_word
    progress = Array.new(solution.length,"*").join()
    game = Game.new(solution:solution,progress:progress,guess_count:10)
    game.save
    redirect_to :action => 'play' , :id =>game.id
    
  end
  
  def play
    @game = Game.find(params[:id])
  end
  
  def update
    game = Game.find(params[:id])
    
    if game.guess_count > 0
      
      
      guess = params[:guess]
      progress = game.progress
      if game.solution.include? guess
        game.solution.chars.each_with_index do |letter,i|
          if letter == guess
            progress[i] = letter
    				
          end
        end
        game.update_attributes(progress: progress)    
      else
      	game.update_attributes(guess_count: game.guess_count-1)	
      end     

      
    end
    redirect_to :action => 'play' , :id =>game.id
  end  
  
  def stats
  	@games = Game.all
  	@wins = Game.where("guess_count >= 0 AND solution = progress").count 
		@losses = Game.where("guess_count <= 0").count
		

  end  
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Hangman App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  
  
  def progressForDisplay(progressStr)
    displayStr = Array.new(progressStr.length)
    progressStr.chars.each_with_index do |letter,i|
    	if letter == "*"
    		displayStr[i] = "  __  "
    	else
    		displayStr[i] = letter
    	end	
    end
    return displayStr.join()
    
  end
  
  def isOver(game)
  	return won(game) || lost(game)
  end
  
  def lost(game)
  	return game.guess_count < 1 && (game.solution != game.progress)
  end
  
  def won(game)
  	return (game.solution == game.progress)
  end
  
  def showHangman(num)
  	if num < 0
  		num = 0
  	end
  	return image_tag("hangmen/"+num.to_s+".png")
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/games/new.html.erb
<% provide(:title, "Play") %>

app/views/games/play.html.erb
<% provide(:title, "Play") %>

<h1><%= progressForDisplay(@game.progress) %></h1>

<h2>
	Incorrect guesses: <%= 10-@game.guess_count %>
</h2>

<center>

	<% if won(@game) %>
  	<h1>You won!</h1>
	<% elsif lost(@game) %>
  	<h1>You lost! Solution: <%= @game.solution %> </h1>
	<% else %>
    <% ('a'..'z').to_a.each do |letter| %>
      <%= link_to letter, update_path({:id => @game.id, :guess => letter}), method: :post, class: "btn btn-sm btn-primary" %>
    <% end %>
	<% end %>

	<% if isOver(@game) %>
		<div>
  		<%= link_to "Play Again", new_path, class: "btn btn-lg btn-primary" %>
		</div>
	<% end %>

	<% num = @game.guess_count %>

<%= showHangman(num) %>

</center>

app/views/games/stats.html.erb
<% provide(:title, "Stats") %>
<h1>Stats</h1>


<p>Total games completed: <b><%= @wins+@losses %></b></p>


<p>Wins: <b><%= @wins %></b></p>

<p>Losses: <b><%= @losses %></b></p>

app/views/games/update.html.erb
render play

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "hangman", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Play",   new_path %></li>
        <li><%= link_to "Stats",   stats_path %></li>
        <li><%= link_to "About",  about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is my first <a href="http://rubyonrails.org"><em>Ruby on Rails
  </em></a> application.
</p>
<p>
  Resources include
  <a href="http://www.railstutorial.org/book">Rails Tutorial</a> and
  <a href="http://www.heroku.com/">Heroku</a>.
</p>
<p>
  You can review my code at 
  <a href="https://bitbucket.org/malison13/hangman_1/src">Bitbucket.org</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Hangman</h1>

  <h2>
    This is the home page.
  </h2>

  <%= link_to "Start game!", new_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("gallows.png", alt: "gallows"), new_path %>